version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: expense-tracker-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: expense-tracker-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads

volumes:
  mongo_data:
